### ISSUE TITLE
Frame not defined

### ISSUE THREAD

**Issue by solitary8** [Jukebox288/CustomTkinter_ConsoleOutput_GUI#1]
In this line of code I get an error with a comment saying frame is not defined :  
```
console_text = customtkinter.CTkTextbox(frame, wrap=tk.WORD, width=500, height=500)

```

**Comment by Jukebox288** [comment]
In the code "frame" is created as a parent for the console_text textbox here:

```
frame = customtkinter.CTkFrame(master=root)
frame.pack(pady=10, padx=10, fill="both", expand=True)
```

If you are adapting the textbox to your own code and you do not want to use "frame" as the parent frame, you can replace it with root or the name of your own parent frame.

**Comment by solitary8** [comment]
I replaced it with root but the text box is too big so I made it smaller and then I got error because I gave the path to my script where the command is executed (a command executed with subprocess) but it didn't work I got no such file or directory error.

**Comment by Jukebox288** [comment]
In that case make sure to use a direct path to the script file. Such as:

`script_path = r"C:\Users\User\your_script.py"`

Apologies for getting to this so late.

**Comment by solitary8** [comment]
Don't worry,anyways I just decided to open a new terminal run the command and output the results and then closes but I'll try it,thanks for your help !
